import LOGO_NAV_BAR from './logo_nav_bar.png'
import BG_BLACK_HOLE from './blackhole_static.webp'
import CONST_SARG from './constelacao_sagittarius.png'
import RUPESTRE_SOL from './rupestre_sol.png'
import BURACOS_NEGROS from './buracos_negros.webp'
import OBSERVACAO from './observacao.webp'
import MINICURSO_ASTRO from './minicurso_astronomia.webp'
import CERT_MCTI_IMG from './cert_mcti_img.webp'
import CERT_NOITE_ESTRELAS_IMG from './cert_noite_com_as_estrelas_img.webp'
import ARTIGO_REVISTA_EXITUS from './artigo_revista_exitus.webp'
import APRES_ESCOLA_CARLOTA from './apresentacao_escola_carlota.webp'
import ARTIGO_REVISTA_RBECM from './artigo_revista_rbecm.webp'
import GLOBO_PLASMA from './globo_plasma.jpg'
import TELESCOPIO from './telescopio.png'
import INTERVENSAO_ASTRO from './intervencao_astronomica.webp'
import SOL from './sol.webp'
import LUA from './lua.jpeg'
import PICO_GAVIAO from './pico_do_gaviao_capao.webp'
import MORRAO from './morrao.jpeg'
import BORBOREMA from './borborema.jpeg'
import ALE_CAMISETAS from './ale_camisetas.png'
import CAMISETA from './camiseta.png'
import PITEIRAS from './piteiras.png'


export { LOGO_NAV_BAR, ARTIGO_REVISTA_RBECM, APRES_ESCOLA_CARLOTA, CERT_MCTI_IMG, ARTIGO_REVISTA_EXITUS, BURACOS_NEGROS, OBSERVACAO, BG_BLACK_HOLE, CONST_SARG, RUPESTRE_SOL, MINICURSO_ASTRO, CERT_NOITE_ESTRELAS_IMG, GLOBO_PLASMA, TELESCOPIO, INTERVENSAO_ASTRO, SOL, LUA, PICO_GAVIAO, MORRAO, BORBOREMA, ALE_CAMISETAS, CAMISETA, PITEIRAS};