declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.svg';
declare module '*.webm';
declare module '*.mp3';
declare module '*.wav';
declare module '*.ogg';
